name: Security Hub Jira Sync

on:
  schedule:
    - cron: "0 14-23/2 * * *"
  workflow_dispatch:

jobs:
  security-hub-jira-sync:
    name: Security Hub Jira Sync
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # AWS credentials must be provided to get findings from security hub; how you inject credentials can vary.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800

      - run: npm install

      - name: Invoke Security Hub Jira Sync
        env:
          JIRA_HOST: qmacbis.atlassian.net
          JIRA_PROJECT: OY2
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: node run.js
