name: Security Hub Jira Sync

on:
  schedule:
    - cron: "0 14-23/2 * * *"
  workflow_dispatch:

jobs:
  security-hub-jira-sync:
    name: Security Hub Jira Sync
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - run: npm install

      - name: Invoke Security Hub Jira Sync
        env:
          JIRA_HOST: qmacbis.atlassian.net
          JIRA_PROJECT: OY2
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: node run.js
