name: Pre-commit

on:
  pull_request:
  push:

permissions:
  actions: read
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
